title: VIBE Conference 2022
preposition: at
description: >-
  Virtual Institute of Bioinformatics and Evolution, All-Ireland Conference
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://VIBE2022.github.io" # the base hostname & protocol for your site, e.g.  https://example.com
  
#theme: jekyll-theme-conference
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.0"
# Build settings
plugins:
  [jekyll-include-cache]
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  

# Collections and their defaults
collections:
  talks:
    output: false
    permalink: /:collection/:title/
  speakers:
    output: false
    permalink: /:collection/:title/
  rooms:
    output: false
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Virtual Institute of Bioinformatics and Evolution 
      # img: ''
      url: http://www.gen.tcd.ie/vibe/VIBEire/who.html
    links:
      - name: Program
        relative_url: /program/
 #     - name: Talks
 #       relative_url: /talks/
 #     - name: Speakers
 #       relative_url: /speakers/
 #     - name: Location
 #       relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2022 (current)
            disabled: true
          - name: 2020
            relative_url: http://www.gen.tcd.ie/vibe/


  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      - name: Register
        disabled: true
        absolute_url: 'https://bit.ly/RegisterVIBE'
      - name: Submit an abstract
        disabled: true
        absolute_url: 'https://bit.ly/abstractVIBE'	
  # Information boxes
  info_bars:
    - title: VIBE Conference 2022
      color: primary
      main_only: true
      text: University of Limerick, School of Limerick, June 24th 2022
    - text: Conference of VIBE.
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 24.06.2022
    timezone: GMT
    stop:       240  # in minutes
    streaming:
      enable: false
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 52.67846, -8.56815
    map_provider:  "Esri.WorldTopoMap"
    
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
   #   map_provider: "OpenStreetMap.Mapnik"
   #   default_zoom: 19



      
  talks:
    # Talk categories
    main_categories:
      - name: lighning
        color: info
      - name: 10_mintalk
        color: success
      - name: keynote
        color: warning
#      - name: workshop
#        color: dark

    # Hide icons on talk overview page
    hide_icons: true

  speakers:
    # Show first and last name
    show_firstname: false

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false
